## path to tools ##
readCounterScript:  /path/to/readCounter
ichorCNA_rscript:  /path/to/ichorCNA.R
ichorCNA_libdir:
  /path/to/ichorCNA_code
pyCountScript:  code/countPysam.py
TitanCNA_rscript: ../R_scripts/titanCNA.R
TitanCNA_selectSolutionRscript: ../R_scripts/selectSolution.R
TitanCNA_libdir:  ../../R/

## path to reference files ##
ichorCNA_exons:
  NULL
ichorCNA_centromere:
  /path/to/GRCh37.p13_centromere_UCSC-gapTable.txt
refFasta:
  /seq/references/Homo_sapiens_assembly19/v1/Homo_sapiens_assembly19.fasta
snpDB:
  /path/to/hapmap_3.3.b37.vcf
TitanCNA_centromere:  /path/to/GRCh37.p13_centromere_UCSC-gapTable.txt

## params for each step ##

## read depth params ##
chrs:
  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X,Y
binSize:  10000

## ichorCNA params ##
ichorCNA_gcWig: /path/to/gc_hg19_10kb.wig
ichorCNA_mapWig:  /path/to/map_hg19_10kb.wig
ichorCNA_exons:  NULL
ichorCNA_centromere:  NULL
ichorCNA_chrs:  c(1:22, \"X\")
ichorCNA_chrTrain:  c(1:22)  
ichorCNA_normal:  c(0.5)  
ichorCNA_ploidy:  c(2,3)  
ichorCNA_estimateNormal:  TRUE
ichorCNA_estimatePloidy:  TRUE
ichorCNA_estimateClonality: TRUE
ichorCNA_scStates:  c(1,3)
ichorCNA_maxCN:  8
ichorCNA_includeHOMD: FALSE
ichorCNA_txnE:  0.9999
ichorCNA_txnStrength:  10000
ichorCNA_plotFileType:  png
ichorCNA_plotYlim:  c(-2,4)

## allele counts - samtools, pysam ##
#filterHETrscript: code/getPhasedHETSitesFromLLRVCF.R
map_quality:  10
base_quality: 10
vcf_quality:  100

## TitanCNA params ##
TitanCNA_numCores: 1
TitanCNA_maxNumClonalClusters: 2
TitanCNA_chrs:  c(1:22, \"X\")
TitanCNA_normalInit: 0.5
TitanCNA_maxPloidy: 3
TitanCNA_estimateNormal:  map
TitanCNA_estimatePloidy:  TRUE
TitanCNA_estimateClonality: TRUE
TitanCNA_alleleModel: binomial
TitanCNA_alphaK:  10000
TitanCNA_alphaR:  10000
TitanCNA_txnExpLen: 1e15
TitanCNA_plotYlim:  c(-2,4)
TitanCNA_solutionThreshold: 0.05

