## path to tools
samTools:  /path/to/samtools
bcfTools:  /path/to/bcftools

## path to scripts ##
readCounterScript:  /path/to/readCounter
ichorCNA_rscript:  /path/to/ichorCNA.R
ichorCNA_libdir:  /path/to/ichorCNA_code
pyCountScript:  code/countPysam.py
TitanCNA_rscript: ../R_scripts/titanCNA.R
TitanCNA_combineTitanIchorCNA:  code/combineTITAN-ichor.R
TitanCNA_selectSolutionRscript: ../R_scripts/selectSolution.R
TitanCNA_libdir:  ../../R/

## reference settings and paths to reference files ##
genomeBuild: hg19
genomeStyle:  NCBI
refFasta:  /path/to/Homo_sapiens_assembly19.fasta
snpVCF:  /path/to/hapmap_3.3.b37.vcf.gz 
ichorCNA_exons: NULL
cytobandFile:  None # only need if hg38
centromere:  /path/to/ichorCNA/inst/extdata/GRCh37.p13_centromere_UCSC-gapTable.txt
sex:  male   # use None if both females and males are in sample set

## params for each step ##

## read depth params ##
# use this for NCBI chr naming
chrs: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X,Y 
# use this for UCSC chr naming
#chrs: chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrY 
binSize:  10000

## ichorCNA params ##
ichorCNA_gcWig: /path/to/gc_hg19_10kb.wig
ichorCNA_mapWig:  /path/to/map_hg19_10kb.wig
ichorCNA_chrs:  c(1:22, \"X\")
ichorCNA_normal:  c(0.5)  
ichorCNA_ploidy:  c(2,3)  
ichorCNA_estimateNormal:  TRUE
ichorCNA_estimatePloidy:  TRUE
ichorCNA_estimateClonality: TRUE
ichorCNA_scStates:  c(1,3)
ichorCNA_maxCN:  8
ichorCNA_includeHOMD: FALSE
ichorCNA_txnE:  0.9999
ichorCNA_txnStrength:  10000
ichorCNA_plotFileType:  png
ichorCNA_plotYlim:  c(-2,4)

## allele counts - samtools, pysam ##
# USERS MUST MODIFY getAlleleCounts.snakefile to use the correct CHRS naming
map_quality:  10
base_quality: 10
vcf_quality:  100

## TitanCNA params ##
TitanCNA_maxNumClonalClusters: 2
TitanCNA_chrs:  c(1:22, \"X\")
TitanCNA_normalInit: 0.5
TitanCNA_maxPloidy: 3
TitanCNA_estimateNormal:  map
TitanCNA_estimatePloidy:  TRUE
TitanCNA_estimateClonality: TRUE
TitanCNA_alleleModel: binomial
TitanCNA_alphaK:  10000
TitanCNA_alphaR:  10000
TitanCNA_txnExpLen: 1e15
TitanCNA_plotYlim:  c(-2,4)
TitanCNA_solutionThreshold: 0.05
TitanCNA_numCores: 1

## Combine TitanCNA & ichorCNA
mergeIchorHOMD: FALSE  # consider setting to TRUE when working with pure tumor

